server {
    listen 80;
    root /usr/share/nginx/html;

    location = /newrelic {
        return 301 /newrelic/;
    }

    location /newrelic {
        alias /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /newrelic/index.html;
    }
}
